#!/bin/sh
# SELF policy: only the primary WAN pair can schedule a coalesced DNS restart.
[ "$ACTION" = ifup ] || exit 0
case "$INTERFACE" in wan|wan6) ;; *) exit 0 ;; esac
[ -x /usr/libexec/swrt-mosdns-hotplug ] || exit 0
/usr/libexec/swrt-mosdns-hotplug schedule
exit 0
