#!/bin/sh

[ "$ACTION" = ifup ] || [ "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate ] && [ -z "$IFUPDATE_ADDRESSES" ] && [ -z "$IFUPDATE_DATA" ] && exit 0

if echo "$INTERFACE" | grep -q "wan" && echo "$INTERFACE" | grep -qv "vap"; then
    IPV6_REGEX="\(\([0-9A-Fa-f]\{1,4\}:\)\{1,\}\)\(\([0-9A-Fa-f]\{1,4\}\)\{0,1\}\)\(\(:[0-9A-Fa-f]\{1,4\}\)\{1,\}\)"
    IPV6_ADDR="$(ip -6 addr show dev "$DEVICE" | grep inet6 | grep -m 1 -o "$IPV6_REGEX")"

    if [ -n "$IPV6_ADDR" ]; then
        (
            LOCK_FILE="/tmp/lock/odhcpd_hotplug_lock"
            if [ -f "$LOCK_FILE" ]; then
                exit 1
            else
                echo $$ > "$LOCK_FILE" 2>/dev/null
                trap 'rm -f "$LOCK_FILE"' EXIT
                sleep 30
                [ -f '/etc/init.d/miniupnpd' ] && "/etc/init.d/miniupnpd" stop 2>&1
                "/sbin/ifup" lan 2>&1
                [ -f '/etc/init.d/miniupnpd' ] && "/etc/init.d/miniupnpd" start 2>&1
                logger -t odhcpd "Reloading lan due to $ACTION of $INTERFACE ($DEVICE)"
            fi
        ) &
    fi
fi
